Numpy(Numerical Python): 파이썬에서 대규모 다차원 배열을 다룰 수 있게 도와주는 라이브러리

In [1]:
## list와 array의 차이
## list: 콤마로 구분, class는 list
## array(numpy): 공백으로 구분, class는 numpy.ndarray(n-dimension array)

# list 형식으로 출력
list_array =list(range(5))
print(list_array)
print(type(list_array))
print()

# numpy 형식으로 출력
import numpy as np
np_array = np.array(range(5))
print(np_array)
print(type(np_array))

[0, 1, 2, 3, 4]
<class 'list'>

[0 1 2 3 4]
<class 'numpy.ndarray'>


In [2]:
## numpy의 배열의 데이터 타입 dtype
## numpy의 배열은 리스트와 달리 같은 데이터 타입(단일 데이터)만 저장 가능하다.
arr = np.array(range(5),dtype = float)
print(arr)
print(arr.dtype)
print(arr.astype(int))

## dtype의 종류: int,float,str,bool
# int(정수형) : i, int_, int32, int64 = i8
# float(실수형) : f, float_, float32, float64 = f8
# str(문자열) : str, U, U32
# bool(부울) : ?, bool_





[0. 1. 2. 3. 4.]
float64
[0 1 2 3 4]


In [3]:
## 배열의 차원 관련 속성: ndim, shape, size, len()
# ndim(n-dimension): 배열이 몇차원인지를 반환
# shape: 배열의 모양을 튜플로 반환
# size: 배열 요소의 수를 반환
# len(): 배열의 길이(행의 개수)를 반환

list1 = [0,1,2,3]
arr1 = np.array(list1)
print(arr1.ndim)
print(arr1.shape)
print(arr1.size)
print(len(arr1))
print()

list2 = [[0,1,2],[3,4,5]]
arr2 = np.array(list2)
print(arr2.ndim)
print(arr2.shape)
print(arr2.size)
print(len(arr2))

1
(4,)
4
4

2
(2, 3)
6
2


In [4]:
## 배열의 모양의 변환

arr = np.array([0,1,2,3,4,5])
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(len(arr))
print("\n---변경 후---\n")

arr.shape = (3,2)  # 괄호 생략 가능
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(len(arr))



[0 1 2 3 4 5]
1
(6,)
6
6

---변경 후---

[[0 1]
 [2 3]
 [4 5]]
2
(3, 2)
6
3


In [5]:
## arange(a,b,c) 함수: a부터 b-1까지 c씩 증가하는 배열
## 인덱싱(indexing): 인덱스로 값을 찾아낸다

# 1차원에서의 indexing
x = np.arange(7)
print(x)
print(x[3])
#print(x[7])  IndexError 발생
x[0]=10  # 인덱스로 값을 변경 가능
print(x)
print()

# 2차원에서의 indexing (인덱스는 0부터 시작함을 주의)
y = np.arange(1,13,1)
y.shape = 3,4
print(y)
print(y[2,3])


[0 1 2 3 4 5 6]
3
[10  1  2  3  4  5  6]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
12


In [6]:
## 슬라이싱(slicing): 인덱스의 값으로 배열의 일부분을 가져온다

# 1차원에서의 slicing
x = np.arange(7)
print(x)
print(x[1:4])
print(x[1:])
print(x[:4])
print(x[::2])
print()

# 2차원에서의 slicing
y = np.arange(1,13,1)
y.shape = 3,4

print(y)
print(y[1:2,:2:3])
print(y[1:,:2])

[0 1 2 3 4 5 6]
[1 2 3]
[1 2 3 4 5 6]
[0 1 2 3]
[0 2 4 6]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[5]]
[[ 5  6]
 [ 9 10]]


In [ ]:
## Fancy indexing: index 리스트을 전달하여 index에 해당하는 각 요소를 반환한다
## 인덱스 리스트 -> 각 인덱스에 해당하는 값의 배열

x = np.arange(7)
print(x)
print(x[[1,3,5]])
print()

y = np.arange(1,13,1).reshape(3,4)
print(y)
print(y[[0,2]])


[0 1 2 3 4 5 6]
[1 3 5]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 9 10 11 12]]


In [ ]:
# 종합 (인덱싱, 슬라이싱, 팬시 인덱싱)

x = np.arange(1,13,1).reshape(3,4)
print(x)
print(x[1:2,2])
print(x[[0,2],2])
print(x[[0,2],:2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[7]
[ 3 11]
[[ 1  2]
 [ 9 10]]


In [ ]:
# Boolean mask: 배열의 각 요소에 참/거짓을 부여하여 구성된 배열

x = np.arange(7)
print(x)
print(x<3)
print()

## Boolean indexing: 배열의 각 요소의 선택 여부를 Boolean mask를 이용하여 지정한다
## Boolean mask의 True 요소에 해당하는 index를 조회한다
print(x[x<3])
print(x[x%2==0])


[0 1 2 3 4 5 6]
[ True  True  True False False False False]

[0 1 2]
[0 2 4 6]
